# Generated by Django 4.2.6 on 2023-10-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=10)),
                ('motto', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('psd', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
