# Generated by Django 4.2.6 on 2023-10-30 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bulletin', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('classIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XtExam.class')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tips', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MC', 'MultiCho'), ('MR', 'MultiRes'), ('FB', 'Blank'), ('SB', 'Subjective')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt', models.CharField(max_length=500)),
                ('options', models.CharField(max_length=500)),
                ('standard_answer', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=10)),
                ('motto', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XtExam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XtExam.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_number', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XtExam.exampaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XtExam.question')),
            ],
        ),
        migrations.AddField(
            model_name='exampaper',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XtExam.userprofile'),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='questions',
            field=models.ManyToManyField(through='XtExam.ExamSchema', to='XtExam.question'),
        ),
        migrations.AddField(
            model_name='exam',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='XtExam.userprofile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XtExam.exampaper'),
        ),
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.ManyToManyField(through='XtExam.Participation', to='XtExam.userprofile'),
        ),
        migrations.AddField(
            model_name='class',
            name='members',
            field=models.ManyToManyField(to='XtExam.userprofile'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='XtExam.userprofile'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_score', models.IntegerField()),
                ('ans_type', models.CharField(choices=[('MC', 'MultiCho'), ('MR', 'MultiRes'), ('FB', 'Blank'), ('SB', 'Subjective')], max_length=20)),
                ('choice_ans', models.CharField(blank=True, max_length=50, null=True)),
                ('text_ans', models.CharField(blank=True, max_length=2048, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XtExam.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XtExam.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XtExam.userprofile')),
            ],
        ),
    ]
